[book]
authors = ["Ladislav Bartos"]
description = "Manual for the gorder tool"
language = "en"
src = "src"
title = "gorder manual"

[preprocessor.katex]
after = ["links"]

[output.html]
input-404 = "not_found.md"
mathjax-support = true
